/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by TanStack Router on first `npm run dev`.
// Stub so the project can typecheck / build before the first generation.

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";

const IndexRouteWithChildren = IndexRoute;

export interface FileRoutesByPath {
  "/": {
    id: "/";
    path: "/";
    fullPath: "/";
    preLoaderRoute: typeof IndexRoute;
    parentRoute: typeof rootRoute;
  };
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
  }
}

const rootRouteChildren = {
  IndexRoute: IndexRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRoutesByPath>();
